//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.7.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.DemosTelerik
{
    [Screen]
    public partial class EditableTableScreen : Progile.TRIO.BaseModel.BaseScreen
    {
        public EditableTableScreen(AutoScout24App app) : base(app, @"Editable Table Screen", Images.DemosTelerik.EditableTableScreen.Screen_Loaded)
        {
            App = app;
            ExampleTable = new ExampleTable(app) { ParentElement = this };
            AddNewRecordButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "AddNewRecordButton", activeImageReference: Images.DemosTelerik.EditableTableScreen.AddNewRecordButton.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            DeleteRowButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "DeleteRowButton", activeImageReference: Images.DemosTelerik.EditableTableScreen.DeleteRowButton.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            NewProductNameTextbox = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "NewProductNameTextbox", imageReference: Images.DemosTelerik.EditableTableScreen.NewProductNameTextbox, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            DeleteRecordConfirmation = new Progile.TRIO.BaseModel.LabelWithButton(tester: t, displayName: "DeleteRecordConfirmation", buttonPosition: RelativePosition.Below, imageReferenceForLabel: Images.DemosTelerik.EditableTableScreen.DeleteRecordConfirmation.LabelImage, buttonActiveimageReference: Images.DemosTelerik.EditableTableScreen.DeleteRecordConfirmation.Button.active, filters: ScreenSelect) { ParentElement = this };
            NewProductNameTextbox.PressEnterAfterType = true;

            ConfigureElementProperties();
        }


        private AutoScout24App App { get; set; }
        public ExampleTable ExampleTable { get; private set; }

        public Progile.TRIO.BaseModel.Button AddNewRecordButton { get; private set; }

        public Progile.TRIO.BaseModel.Button DeleteRowButton { get; private set; }

        public Progile.TRIO.BaseModel.TextBox NewProductNameTextbox { get; private set; }

        public Progile.TRIO.BaseModel.LabelWithButton DeleteRecordConfirmation { get; private set; }

        partial void ConfigureElementProperties();
    }
}