//------------------------------------------------------------------------------
//
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.2.0
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// </auto-generated>
//
//------------------------------------------------------------------------------

using System;
using Progile.TRIO.BaseModel;
using Progile.ATE.TestFramework;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.DemosTelerik
{
	[Table]
	public partial class ExampleTable : TableBase<Column, Row>
	{
		public ExampleTable(AutoScout24App app) : base(app, "ExampleTable", Images.DemosTelerik.EditableTableScreen.ExampleTable.TableLoadedImage)
		{
			App = app;
			ColumnProductName = new Column(t, "ColumnProductName", Images.DemosTelerik.EditableTableScreen.ExampleTable.ColumnProductName, TableRect) {ParentElement = this};
			ColumnUnitPrice = new Column(t, "ColumnUnitPrice", Images.DemosTelerik.EditableTableScreen.ExampleTable.ColumnUnitPrice, TableRect) {ParentElement = this};
			ColumnUnitsInStock = new Column(t, "ColumnUnitsInStock", Images.DemosTelerik.EditableTableScreen.ExampleTable.ColumnUnitsInStock, TableRect) {ParentElement = this};
			ColumnDiscontinued = new Column(t, "ColumnDiscontinued", Images.DemosTelerik.EditableTableScreen.ExampleTable.ColumnDiscontinued, TableRect) {ParentElement = this};

			ConfigureElementProperties();
		}

		private AutoScout24App App;

		[ModelCapability]
		public Column ColumnProductName { get; private set; }

		[ModelCapability]
		public Column ColumnUnitPrice { get; private set; }

		[ModelCapability]
		public Column ColumnUnitsInStock { get; private set; }

		[ModelCapability]
		public Column ColumnDiscontinued { get; private set; }

		partial void ConfigureElementProperties();
	}
}
