//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.7.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Windows;

namespace Windows_Model.Screens
{
    [Screen]
    public partial class FileProperties : Progile.TRIO.BaseModel.BaseScreen
    {
        public FileProperties(WindowsApp app) : base(app, @"FileProperties", Images.FileProperties.Screen_Loaded)
        {
            App = app;

            ConfigureElementProperties();
        }


        private WindowsApp App { get; set; }
        partial void ConfigureElementProperties();
    }
}