//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.7.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Windows;

namespace Windows_Model.Screens
{
    [Screen]
    public partial class FileExplorer : Progile.TRIO.BaseModel.BaseScreen
    {
        public FileExplorer(WindowsApp app) : base(app, @"FileExplorer", Images.FileExplorer.Screen_Loaded)
        {
            App = app;
            DesktopLabel = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Desktop Label", imageReference: Images.FileExplorer.DesktopLabel, filters: ScreenSelect) { ParentElement = this };
            FileContextMenu = new Progile.TRIO.BaseModel.ContextMenu(appBasics: AppBasics, displayName: "File Context Menu", imageReference: Images.FileExplorer.FileContextMenu) { ParentElement = this };

            ConfigureElementProperties();
        }


        private WindowsApp App { get; set; }
        public Progile.TRIO.BaseModel.Label DesktopLabel { get; private set; }

        public Progile.TRIO.BaseModel.ContextMenu FileContextMenu { get; private set; }

        partial void ConfigureElementProperties();
    }
}