//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.6.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using AutoScout24_Model.Screens.AutoScout24Screens;
using AutoScout24_Model.Screens.DemosTelerik;
using AutoScout24_Model.Screens.TruckScout24Screens;
using AutoScout24_Model.Screens.Scout24_comScreens;

namespace AutoScout24_Model
{
    [SoftwareModel]
    public partial class AutoScout24App : IAppBasics
    {
        partial void InitScreens()
        {
            CarPreview = new CarPreview(this);
            DetailSearch = new DetailSearch(this);
            EditableTableScreen = new EditableTableScreen(this);
            LoginPage = new LoginPage(this);
            MainPage = new MainPage(this);
            SearchResults = new SearchResults(this);
            SharePriceScreen = new SharePriceScreen(this);
        }


        public CarPreview CarPreview { get; set; }
        
        public DetailSearch DetailSearch { get; set; }
        
        public EditableTableScreen EditableTableScreen { get; set; }
        
        public LoginPage LoginPage { get; set; }
        
        public MainPage MainPage { get; set; }
        
        public SearchResults SearchResults { get; set; }
        
        public SharePriceScreen SharePriceScreen { get; set; }
        
    }
}