//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.3.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.AutoScout24Screens
{
    [Screen]
    public partial class MainPageCars : Progile.TRIO.BaseModel.BaseScreen
    {
        public MainPageCars(AutoScout24App app) : base(app, @"Main Page Cars", Images.AutoScout24Screens.MainPageCars.Screen_Loaded)
        {
            App = app;
            RefineSearchLink = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Refine search Link", activeImageReference: Images.AutoScout24Screens.MainPageCars.RefineSearchLink.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            ResultsButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "ResultsButton", activeImageReference: Images.AutoScout24Screens.MainPageCars.ResultsButton.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            PriceUpToDropdown = new Progile.TRIO.BaseModel.Dropdown(appBasics: AppBasics, displayName: "PriceUpToDropdown", imageReference: Images.AutoScout24Screens.MainPageCars.PriceUpToDropdown.DropdownTextBox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            Make = new Progile.TRIO.BaseModel.Dropdown(appBasics: AppBasics, displayName: "Make", imageReference: Images.AutoScout24Screens.MainPageCars.Make.DropdownTextBox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            Model = new Progile.TRIO.BaseModel.Dropdown(appBasics: AppBasics, displayName: "Model", imageReference: Images.AutoScout24Screens.MainPageCars.Model.DropdownTextBox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            FirstRegistration = new Progile.TRIO.BaseModel.Dropdown(appBasics: AppBasics, displayName: "First registration", imageReference: Images.AutoScout24Screens.MainPageCars.FirstRegistration.DropdownTextBox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            NumberOfResultsLabelWithValue = new Progile.TRIO.BaseModel.LabelWithValue(tester: t, displayName: "NumberOfResults LabelWithValue", valuePosition: RelativePosition.Left, imageReferenceForLabel: Images.AutoScout24Screens.MainPage.NumberOfResultsLabelWithValue, gridWidth: 200, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private AutoScout24App App { get; set; }
        public Progile.TRIO.BaseModel.Button RefineSearchLink { get; private set; }

        public Progile.TRIO.BaseModel.Button ResultsButton { get; private set; }

        public Progile.TRIO.BaseModel.Dropdown PriceUpToDropdown { get; private set; }

        public Progile.TRIO.BaseModel.Dropdown Make { get; private set; }

        public Progile.TRIO.BaseModel.Dropdown Model { get; private set; }

        public Progile.TRIO.BaseModel.Dropdown FirstRegistration { get; private set; }

        public Progile.TRIO.BaseModel.LabelWithValue NumberOfResultsLabelWithValue { get; private set; }

        partial void ConfigureElementProperties();
    }
}