//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.AutoScout24Screens
{
    [Screen]
    public partial class SearchResults : Progile.TRIO.BaseModel.BaseScreen
    {
        public SearchResults(IAppBasics appBasics) : base(appBasics, @"Search Results", Images.AutoScout24Screens.SearchResults.Screen_Loaded)
        {
            OffersFound = new Progile.TRIO.BaseModel.LabelWithValue(tester: t, displayName: "Offers found", valuePosition: RelativePosition.Left, imageReferenceForLabel: Images.AutoScout24Screens.SearchResults.OffersFound, gridWidth: 125, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        public Progile.TRIO.BaseModel.LabelWithValue OffersFound { get; private set; }

        partial void ConfigureElementProperties();
    }
}