//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.WindowsOS
{
    [Screen]
    public partial class FileExplorer : Progile.TRIO.BaseModel.BaseScreen
    {
        public FileExplorer(IAppBasics appBasics) : base(appBasics, @"FileExplorer", Images.WindowsOS.FileExplorer.Screen_Loaded)
        {
            DesktopLabel = new Progile.TRIO.BaseModel.Label(tester: t, displayName: "Desktop Label", imageReference: Images.WindowsOS.FileExplorer.DesktopLabel, filters: ScreenSelect) { ParentElement = this };
            FileContextMenu = new Progile.TRIO.BaseModel.ContextMenu(appBasics: AppBasics, displayName: "File Context Menu", imageReference: Images.WindowsOS.FileExplorer.FileContextMenu) { ParentElement = this };

            ConfigureElementProperties();
        }


        public Progile.TRIO.BaseModel.Label DesktopLabel { get; private set; }

        public Progile.TRIO.BaseModel.ContextMenu FileContextMenu { get; private set; }

        partial void ConfigureElementProperties();
    }
}