//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.WindowsOS
{
    [Screen]
    public partial class FileProperties : Progile.TRIO.BaseModel.BaseScreen
    {
        public FileProperties(IAppBasics appBasics) : base(appBasics, @"FileProperties", Images.WindowsOS.FileProperties.Screen_Loaded)
        {

            ConfigureElementProperties();
        }


        partial void ConfigureElementProperties();
    }
}