//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.7.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.AutoScout24_deScreens
{
    [Screen]
    public partial class Autohändler : Progile.TRIO.BaseModel.BaseScreen
    {
        public Autohändler(AutoScout24App app) : base(app, @"Autohändler", Images.AutoScout24_deScreens.Autohändler.Screen_Loaded)
        {
            App = app;

            ConfigureElementProperties();
        }


        private AutoScout24App App { get; set; }
        partial void ConfigureElementProperties();
    }
}