//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.AutoScout24_deScreens
{
    [Screen]
    public partial class Autohändler : Progile.TRIO.BaseModel.BaseScreen
    {
        public Autohändler(IAppBasics appBasics) : base(appBasics, @"Autohändler", Images.AutoScout24_deScreens.Autohändler.Screen_Loaded)
        {

            ConfigureElementProperties();
        }


        partial void ConfigureElementProperties();
    }
}