//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.2.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.TruckScout24Screens
{
    [Screen]
    public partial class MembersLoginPage : Progile.TRIO.BaseModel.BaseScreen
    {
        public MembersLoginPage(AutoScout24App app) : base(app, @"Members Login Page", Images.TruckScout24Screens.MembersLoginPage.Screen_Loaded)
        {
            App = app;
            UsernameTextbox = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Username Textbox", imageReference: Images.TruckScout24Screens.MembersLoginPage.UsernameTextbox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            PasswordTextbox = new Progile.TRIO.BaseModel.PwTextBox(appBasics: AppBasics, displayName: "Password Textbox", imageReference: Images.TruckScout24Screens.MembersLoginPage.PasswordTextbox, useVisualSense: false, pwCharImage: Images.Common.BlindCharImage, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private AutoScout24App App { get; set; }
        public Progile.TRIO.BaseModel.TextBox UsernameTextbox { get; private set; }

        public Progile.TRIO.BaseModel.PwTextBox PasswordTextbox { get; private set; }

        partial void ConfigureElementProperties();
    }
}