//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.3.5.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.TruckScout24Screens
{
    [Screen]
    public partial class TruckscoutMainPage : Progile.TRIO.BaseModel.BaseScreen
    {
        public TruckscoutMainPage(AutoScout24App app) : base(app, @"Truckscout Main Page", Images.TruckScout24Screens.TruckscoutMainPage.Screen_Loaded)
        {
            App = app;
            SellNowButton = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "Sell Now Button", activeImageReference: Images.TruckScout24Screens.TruckscoutMainPage.SellNowButton.active, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            CanScrollToFindElement = true;

            ConfigureElementProperties();
        }


        private AutoScout24App App { get; set; }
        public Progile.TRIO.BaseModel.Button SellNowButton { get; private set; }

        partial void ConfigureElementProperties();
    }
}