//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens.TruckScout24Screens
{
    [Screen]
    public partial class TruckscoutMainPage : Progile.TRIO.BaseModel.BaseScreen
    {
        public TruckscoutMainPage(IAppBasics appBasics) : base(appBasics, @"Truckscout Main Page", Images.TruckScout24Screens.TruckscoutMainPage.Screen_Loaded)
        {
            SellNowButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Sell Now Button", activeImageReference: Images.TruckScout24Screens.TruckscoutMainPage.SellNowButton.active, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        public Progile.TRIO.BaseModel.Button SellNowButton { get; private set; }

        partial void ConfigureElementProperties();
    }
}