//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.2.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.AutoScout24;

namespace AutoScout24_Model.Screens
{
    [Screen]
    public partial class MainMenu : Progile.TRIO.BaseModel.BaseScreen
    {
        public MainMenu(IAppBasics appBasics) : base(appBasics, @"Main Menu", Images.MainMenu.Screen_Loaded)
        {
            MenuButton = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Menu Button", activeImageReference: Images.MainMenu.MenuButton.active, inactiveImageReference: Images.MainMenu.MenuButton.inactive, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            UsedAndNewCars = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Used and New Cars", activeImageReference: Images.MainMenu.UsedAndNewCars.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            Motorbikes = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Motorbikes", activeImageReference: Images.MainMenu.Motorbikes.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            Trucks = new Progile.TRIO.BaseModel.Button(tester: t, displayName: "Trucks", activeImageReference: Images.MainMenu.Trucks.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        public Progile.TRIO.BaseModel.Button MenuButton { get; private set; }

        public Progile.TRIO.BaseModel.Button UsedAndNewCars { get; private set; }

        public Progile.TRIO.BaseModel.Button Motorbikes { get; private set; }

        public Progile.TRIO.BaseModel.Button Trucks { get; private set; }

        partial void ConfigureElementProperties();
    }
}